# Generated by Django 5.2 on 2025-05-06 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='None', max_length=256)),
                ('description', models.TextField(blank=True, default='None', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='None', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='None', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='None', max_length=256)),
                ('description', models.TextField(default='None', max_length=256)),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='job_posts', to='jobs.profession')),
                ('profession_category', models.ManyToManyField(related_name='job_posts', to='jobs.professioncategory')),
            ],
        ),
    ]
