# Generated by Django 5.2 on 2025-05-07 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobpost_expired_userjobpostapplication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userjobpostapplication',
            name='jobpost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_applicants', to='jobs.jobpost'),
        ),
    ]
