# Generated by Django 5.2 on 2025-05-15 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_userjobpostapplication_jobpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userjobpostapplication',
            old_name='date_of_application',
            new_name='date_of_posting',
        ),
    ]
