# Generated by Django 5.2 on 2025-05-15 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_rename_date_of_application_userjobpostapplication_date_of_posting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userjobpostapplication',
            old_name='date_of_posting',
            new_name='date_of_application',
        ),
    ]
