# Generated by Django 5.2 on 2025-05-15 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_rename_date_of_posting_userjobpostapplication_date_of_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='profession',
            name='profession_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='category_professions', to='jobs.professioncategory'),
        ),
    ]
