# Generated by Django 5.2 on 2025-05-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_jobpost_contract_type_jobpost_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='contract_type',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='salary',
            field=models.CharField(default='', max_length=256),
        ),
    ]
