# Generated by Django 5.2 on 2025-05-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_alter_jobpost_contract_type_alter_jobpost_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='city',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='company',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_type',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='work_location',
            field=models.CharField(default='', max_length=256),
        ),
    ]
